vert-x3/vertx-starter

- .gitignore
- vertx-starter-generator/src/main/resources/templates/pom.xml.hbs
Adds CommandFactory to maven shade AppendingTransformer which solves the issue of the fat jar not being executable.
Possibly fixes https://github.com/vert-x3/vertx-starter/issues/44 also  
Also added *.iml files to .gitignore to reduce the noise when developing with IntelliJ
> Fix fat jar executable

- vertx-starter-main/conf/default-conf.json
- vertx-starter-web/src/main/java/io/vertx/starter/web/service/VersionService.java
- vertx-starter-web/src/test/java/io/vertx/starter/web/rest/VersionResourceIntTest.java
Adding vert.x versions 3.5.1 and 3.5.2 and setting the later as the default option.
> Add versions 3.5.1, 3.5.2 and 3.5.3

- dependencies.json
I tried to find as many missing artifactIds as I could.  This is definitely just a stop gap fix.  After looking at the dependencies, I think a feature needs to be added to filter dependencies by Vert.x version as there will be differences both in names as well as what is available.  That will be a larger fix, though.  This will address the narrow issue identified in #35.
> address starter issue #35

- README.md
- build.gradle.kts
- src/main/java/io/vertx/starter/AnalyticsVerticle.java
- src/main/java/io/vertx/starter/GenerationHandler.java
- src/main/java/io/vertx/starter/GeneratorVerticle.java
- src/main/java/io/vertx/starter/WebVerticle.java
- src/main/resources/starter.json
- src/test/java/io/vertx/starter/service/GeneratorTest.java
- new version set: _3.8.0, 3.7.1, 4.0.0-milestone1, 4.0.0-SNAPSHOT_
- upgrade to 3.8 (`Future`/`Promise` and `send`/`request`)
> Follows up on 3.8 release

- src/main/resources/templates/src/main/java/MainVerticle.java.ftl
- src/main/resources/templates/src/main/kotlin/MainVerticle.kt.ftl
Motivation:
I generated a new vertx application using the starter and  I remarked that generating a new project using version 3.9.0 generates a MainVerticle with a start method expecting a deprecated Future argument instead of a Promise. This PR attempts to fix it.
> Generate start method with Promise argument

- src/main/resources/starter.json
- Switch to 4.1.0-SNAPSHOT
- Split monitoring and devops categories
- Added Zipkin and OpenTracing (missing)
- New in 4.1: Infinispan Session Store and OpenTelemetry
> New modules in Vert.x 4.1

- src/main/resources/templates/build.gradle.kts.ftl
Signed-off-by: Olga Ivanova <olga.a.ivanova@inbox.ru>
Motivation:
Fix declaration of repository url in build.gradle.kts.
> fix build.gradle.kts: url in maven repository

- build.gradle.kts
- src/main/resources/templates/build.gradle.kts.ftl
Signed-off-by: Selim Dincer <wowselim@live.de>
Motivation:
This PR removes two references to jcenter as described in https://github.com/vert-x3/vertx-starter/issues/182. It leaves jcenter as repo for the build script of this repo itself but new projects won't include a reference to jcenter any longer.
> ditch jcenter for new projects

- src/main/resources/templates/build.gradle.kts.ftl
- src/main/resources/templates/pom.xml.ftl
Motivation:
This PR bumps the kotlin version to 1.5.0 to make projects work with gradle 7.
> Bump kotlin to 1.5.0

- src/main/resources/templates/build.gradle.kts.ftl
Motivation:
This PR is a migration from mainClassName to mainClass. It seems to be deprecated in the java plugin and it says one should use mainClass instead.
https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaApplication.java#L73
Conformance:
Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines
> Use mainClass instead of mainClassName

- src/main/java/io/vertx/starter/GenerationHandler.java
- src/main/java/io/vertx/starter/WebVerticle.java
All static files (except index) can be cached by browsers for a year (the frontend build adds to each file a suffix that changes with releases).
Compression should be supported (except for already compressed files).
> Improve web performance with compression and caching

- src/main/java/io/vertx/starter/model/Language.java
- src/main/resources/templates/build.gradle.kts.ftl
- src/main/resources/templates/pom.xml.ftl
- src/main/resources/templates/src/main/scala/MainVerticle.scala.ftl
- src/main/resources/templates/src/test/scala/TestMainVerticle.scala.ftl
Motivation:
Generating a project with the Scala language is currently not supported. This change adds Scala support with Maven and Gradle build systems.
Hint:
Before integrating this change, we need a release of [Vert.x Scala support ](https://github.com/vert-x3/vertx-lang-scala).
Closes #118
> Add Scala support

- src/main/frontend/src/components/GenerateButton.vue
Motivation:
GenerateButton will draw the cloverleaf icon on macOS with this change.
Conformance:
I've signed the Eclipse committer agreement.
> Fix macos detection

- README.adoc
- pom.xml
- src/test/java/io/vertx/starter/service/GeneratorTest.java
Closes #475
With these changes, updating the starter.json file will be the only requirement when a new Vert.x version is released.
> Improve vertx version upgrade

- .github/workflows/set-versions.yml
A GitHub actionnable workflow that can bump the stable vertx version and the stable snapshot vertx version
The workflow can be actioned from the Actions tab and requires to provide the stable version an the stable snapshot version, it uses JQ to replace the version in the starter.json configuration file and then push the commit to the branch.
> Set versions workflow

- src/main/resources/starter.json
- src/main/resources/templates/build.gradle.kts.ftl
5.0.0.CR1 has been released and we should propose it instead of 5.0.0-SNAPSHOT
> Vert.x 5 version change: 5.0.0.CR1

- .github/workflows/set-versions.yml
When the stack definition file is updated, the default version of the project must be updated as well.
Otherwise, the starter can't create a project without the user providing the version explicitly.
> Fix the set-versions workflow

- .github/workflows/ci.yml
- src/test/java/io/vertx/starter/service/GeneratorTest.java
At the beginning of the test job, all target JDKs will be installed. The last JDK in the list is the JDK use to build the starter and run the test (Java 17).
In GeneratorTest, we can pick a JDK specific to the generated project target.
> Use specific JDK for generator tests

- .gh.set-versions.bash
- .github/workflows/ci.yml
- .github/workflows/set-versions.yml
To avoid pushing broken commits to the target branch, let's run test as part of the set-versions.yml workflow.
Having the stack modification script separated allows to:
- test it locally
- invoke it several times without repeating commands in the workflow file
> Run tests in set-versions.yml workflow

- src/main/resources/templates/build.gradle.kts.ftl
`watchForChange` and `doOnChange` are only used for the Vert.x 4 launcher.
> Don't include unused variables for Vert.x 5

- src/main/resources/templates/pom.xml.ftl
Motivation:
v5 PgClient depends on the updated com.ongres library (com.ongres.scram:scram-client:3.1) in this PR
Conformance:
My ECA is up to date. I haven't signed this very small change but I'll generate a key and resubmit if necessary.
> Update scram dependency for v5 PgClient
