vertx-starter-web/src/main/resources/webroot/main.js
=> Remove unused options

mongodb.yml, pom.xml, vertx-starter-analytics/pom.xml, vertx-starter-analytics/src/main/java/io/vertx/starter/analytics/AnalyticsVerticle.java, vertx-starter-analytics/src/main/java/io/vertx/starter/analytics/repository/ProjectRepository.java, vertx-starter-analytics/src/main/java/io/vertx/starter/analytics/service/ProjectService.java, vertx-starter-generator/src/main/java/io/vertx/starter/generator/GeneratorVerticle.java, vertx-starter-main/conf/default-conf.json, vertx-starter-main/pom.xml, vertx-starter-main/src/main/java/io/vertx/starter/MainVerticle.java, vertx-starter-web/src/main/java/io/vertx/starter/web/WebVerticle.java, vertx-starter-web/src/main/java/io/vertx/starter/web/rest/StarterResource.java
=> Save project request

README.md, src/main/java/io/vertx/starter/model/Language.java, src/main/java/io/vertx/starter/service/GeneratorService.java, src/main/resources/dependencies.json, src/test/java/io/vertx/starter/service/GeneratorServiceTest.java
- Added `vertx-lang-kotlin` as default dependency for Kotlin
- Added `vertx-lang-kotlin-coroutines` to dependencies
=> Add support for default Vert.x language dependencies

build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Upgraded build plugins and dependencies

README.md, src/main/java/io/vertx/starter/config/ProjectConstants.java, src/main/java/io/vertx/starter/model/VertxProject.java, src/main/java/io/vertx/starter/service/GeneratorService.java, src/main/java/io/vertx/starter/web/rest/StarterResource.java, src/main/resources/application.conf, src/main/resources/templates/build.gradle.ftl, src/main/resources/templates/pom.xml.ftl, src/main/resources/webroot/index.html, src/main/resources/webroot/main.js, src/test/java/io/vertx/starter/service/GeneratorTest.java
=> Custom package name in advanced options

.travis.yml, README.md, build.gradle.kts, src/main/java/io/vertx/starter/config/ProjectConstants.java, src/main/java/io/vertx/starter/model/JdkVersion.java, src/main/java/io/vertx/starter/model/VertxProject.java, src/main/java/io/vertx/starter/service/GeneratorService.java, src/main/java/io/vertx/starter/web/rest/StarterResource.java, src/main/resources/application.conf, src/main/resources/templates/build.gradle.ftl, src/main/resources/templates/pom.xml.ftl, src/main/resources/webroot/index.html, src/main/resources/webroot/main.js, src/test/java/io/vertx/starter/service/GeneratorTest.java
=> Add a switch for JDK version

src/main/java/io/vertx/starter/AnalyticsVerticle.java, src/main/java/io/vertx/starter/GeneratorVerticle.java, src/main/java/io/vertx/starter/VertxProjectCodec.java, src/main/java/io/vertx/starter/WebVerticle.java, src/main/java/io/vertx/starter/model/VertxProject.java, src/main/java/io/vertx/starter/service/AnalyticsService.java, src/main/java/io/vertx/starter/web/rest/StarterResource.java, src/test/java/io/vertx/starter/service/AnalyticsTest.java, src/test/java/io/vertx/starter/service/GeneratorTest.java, src/test/java/io/vertx/starter/web/rest/StarterResourceTest.java
Fixes #94
Also, added VertxProject codec to avoid converting to/from JSON
=> Project stats additions

README.md, build.gradle.kts, src/main/java/io/vertx/starter/service/StarterMetadataService.java, src/main/resources/application.conf, src/test/java/io/vertx/starter/service/GeneratorTest.java
=> Make 3.7.0 the default version

src/main/resources/webroot/index.html, src/main/resources/webroot/main.js
Fixes #87 
Just as Github/Gitlab provides the `git clone` commands to ease developer's job, this PR aims to provide the CLI commands to generate a Vertx project via the starter.
=> Provide in the UI the generation commands with a copy button

src/main/java/io/vertx/starter/WebVerticle.java, src/main/java/io/vertx/starter/config/VerticleConfigurationConstants.java, src/main/java/io/vertx/starter/config/util/ConfigUtil.java, src/main/java/io/vertx/starter/service/GeneratorService.java, src/main/java/io/vertx/starter/web/rest/StarterResource.java, src/main/resources/application.conf, src/main/resources/project-defaults.json, src/main/resources/webroot/main.js, src/test/java/io/vertx/starter/TestMain.java, src/test/java/io/vertx/starter/web/rest/StarterResourceTest.java
=> Remove new project defaults from application.conf

src/main/resources/templates/src/main/java/MainVerticle.java.ftl, src/main/resources/templates/src/main/kotlin/MainVerticle.kt.ftl
See https://github.com/vert-x3/vertx-starter/issues/110
=> for V4.x.x remove future

src/main/resources/templates/src/main/java/MainVerticle.java.ftl, src/main/resources/templates/src/main/kotlin/MainVerticle.kt.ftl
=> Generate start method with Promise argument if version is 3.8.x

README.md, build.gradle.kts, src/main/resources/starter.json, src/test/java/io/vertx/starter/service/GeneratorTest.java
Updated defaults, settings and doc
=> Release 3.8.2

README.md, src/main/java/io/vertx/starter/model/JdkVersion.java, src/main/resources/starter.json, src/main/resources/templates/pom.xml.ftl, src/test/java/io/vertx/starter/MetadataHandlerTest.java
Fix #120
Also fixed wrong docker command in README
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
=> Default JDK selection

src/main/java/io/vertx/starter/service/GeneratorService.java, src/main/resources/templates/build.gradle.kts.ftl, src/main/resources/templates/pom.xml.ftl, src/main/resources/templates/src/test/java/TestMainVerticle.java.ftl, src/main/resources/templates/src/test/kotlin/TestMainVerticle.kt.ftl, src/test/java/io/vertx/starter/service/GeneratorTest.java
=> Generate project with either junit4 or junit5

src/main/resources/starter.json
For https://github.com/eclipse-vertx/vertx-sql-client/issues/696
=> Add vertx-db2-client

src/main/resources/templates/build.gradle.kts.ftl
=> Invalid Gradle doOnChange command

src/main/resources/templates/pom.xml.ftl
=> Replace AppendingTransformer with ServicesResourceTransformer

src/main/java/io/vertx/starter/model/JdkVersion.java, src/test/java/io/vertx/starter/MetadataHandlerTest.java
=> Replace JDK13 option with JDK15

src/main/resources/templates/build.gradle.kts.ftl
=> Gradle: merge any service file

src/main/resources/templates/build.gradle.kts.ftl
=> Gradle: use platform dependency

.github/workflows/ci.yml, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, src/main/resources/files/gradle/gradle/wrapper/gradle-wrapper.properties, src/main/resources/templates/build.gradle.kts.ftl, src/main/resources/templates/pom.xml.ftl, src/test/java/io/vertx/starter/service/GeneratorTest.java
=> Version upgrades

build.gradle.kts
=> Vert.x 4 upgrade

src/main/java/io/vertx/starter/ValidationHandler.java, src/main/java/io/vertx/starter/service/GeneratorService.java, src/main/resources/webroot/index.html, src/main/resources/webroot/main.js, src/test/java/io/vertx/starter/ValidationHandlerTest.java
=> Fail validation if both vertx-unit and vertx-junit5 are selected

src/main/resources/templates/build.gradle.kts.ftl, src/main/resources/templates/pom.xml.ftl
=> Updated OSS Snapshot url

src/main/resources/templates/pom.xml.ftl
=> Remove empty artifactSet from Maven Shade Plugin config

src/main/resources/starter.json, src/main/resources/templates/build.gradle.kts.ftl, src/main/resources/templates/pom.xml.ftl
Updated version and removed workaround for vertx-junit5 issue with 3.9.5
=> 3.9.6 Release

.github/workflows/ci.yml
This reverts commit cfc6b44105f3ed4db4ca81b2d9d4a0937203a08e
=> Revert "Remove JDK15 build temporarily"

.github/workflows/ci.yml, src/main/java/io/vertx/starter/model/JdkVersion.java, src/test/java/io/vertx/starter/MetadataHandlerTest.java, src/test/java/io/vertx/starter/service/GeneratorTest.java
=> Replace JDK15 option with JDK16

src/main/resources/starter.json
Signed-off-by: Paulo Lopes <pmlopes@gmail.com>
Motivation:
Adding vertx-auth-otp
=> Adding vertx-auth-otp

src/main/resources/starter.json
=> Remove 3.9 from the stack definition

src/main/resources/templates/build.gradle.kts.ftl, src/main/resources/templates/pom.xml.ftl
Motivation:
This PR bumps the kotlin version to `1.7.0`
=> Bump kotlin to 1.7

src/main/resources/templates/README.adoc.ftl
Discord is more active than gitter and should be included in this help section
Motivation:
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:
Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines
=> Added link to Discord server

src/main/resources/templates/build.gradle.kts.ftl, src/main/resources/templates/pom.xml.ftl
Motivation:
This PR bumps a whole bunch of outdated versions to their latest:
Kotlin, Junit Jupiter, Junit, Gradle Shadow Jar
Conformance:
Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines
=> Bump versions

src/main/java/io/vertx/starter/WebVerticle.java
- HSTS
- XFrame deny
- CSP
- No content type sniffing
=> Web Security Updates

src/main/java/io/vertx/starter/service/GeneratorService.java, src/main/resources/templates/build.gradle.kts.ftl, src/main/resources/templates/pom.xml.ftl
=> Add SCRAM to projects which depend on Pg Client

README.adoc, pom.xml, src/main/java/io/vertx/starter/AnalyticsVerticle.java, src/main/java/io/vertx/starter/config/VerticleConfigurationConstants.java, src/main/java/io/vertx/starter/service/AnalyticsService.java, src/main/resources/log4j2.xml, src/test/java/io/vertx/starter/service/AnalyticsTest.java, src/test/java/io/vertx/starter/service/GeneratorTest.java
Instead, save a file to a specific directory.
A scheduled job will run on the starter machine to process these files.
=> Remove Mongo dependency

.github/workflows/ci.yml, README.adoc, pom.xml, src/main/java/io/vertx/starter/AnalyticsVerticle.java, src/main/java/io/vertx/starter/GeneratorVerticle.java, src/main/java/io/vertx/starter/ValidationHandler.java, src/main/java/io/vertx/starter/WebVerticle.java, src/main/java/io/vertx/starter/model/Language.java, src/main/java/io/vertx/starter/service/GeneratorService.java, src/main/java/io/vertx/starter/service/TempDir.java, src/test/java/io/vertx/starter/ValidationHandlerTest.java, src/test/java/io/vertx/starter/service/AnalyticsTest.java, src/test/java/io/vertx/starter/service/GeneratorTest.java
The new machine will have the latest Java LTS
=> Upgrade to JDK 17

pom.xml, src/main/java/io/vertx/starter/WebVerticle.java
=> Upgrade to Vert.x 4.4

pom.xml, src/main/scripts/update_db.sh, src/test/java/io/vertx/starter/ScriptsTest.java, src/test/scripts/samples/3d70cc65-a155-4368-a165-c3e29d838a5f, src/test/scripts/samples/80f1f2a8-c2ce-4ac3-8d38-579a439f366f, src/test/scripts/samples/82907346-a14a-4b68-8c8c-2e620e4ef1c5, src/test/scripts/samples/c0f4c5e2-6d53-4704-b63b-b69708552aa9, src/test/scripts/samples/cf6989da-a65a-4ff6-8cda-2930fa785449, src/test/scripts/samples/d0f1f57e-efa3-493b-8f8e-c4c7d33ac191, src/test/scripts/samples/e756a2b5-755a-4a49-88ba-b2d33f342b1e, src/test/scripts/samples/ea755b00-b37b-40b0-85dc-752eee3cc657, src/test/scripts/samples/f42e5a04-6b3d-4e9b-8e64-6df423439b46, src/test/scripts/samples/f50414b1-7bcb-4635-bd74-d7d8caf9800f
The script will be installed on the server.
=> Aggregate project metadata in sqlite file

src/main/resources/starter.json
=> Update Health Check module description

pom.xml, src/main/java/io/vertx/starter/GeneratorVerticle.java, src/test/java/io/vertx/starter/service/AnalyticsTest.java, src/test/java/io/vertx/starter/service/GeneratorTest.java
Also, fix a warnings and replace some deprecated code
=> Bump com.julienviet:childprocess-vertx-ext from 1.3.0 to 2.0.0

src/main/java/io/vertx/starter/service/MetadataHandler.java, src/test/java/io/vertx/starter/MetadataHandlerTest.java
Closes #480
The starter will compute an etag on startup (when metadata is generated). Metadata endpoint responses will have etag and cache control headers set.
This combination allows browsers to:
- reuse the same metadata for one day without sending a request again
- send refresh requests with etag and receive a 304 response if the starter hasn't been updated
=> Let browsers use cached metadata

pom.xml
Upgrade VMP and Commons Compress (CVE)
=> Dependency and plugin upgrade

pom.xml, src/main/resources/starter.json, src/main/resources/templates/README.adoc.ftl, src/main/resources/templates/build.gradle.kts.ftl, src/main/resources/templates/pom.xml.ftl, src/main/resources/templates/src/main/java/MainVerticle.java.ftl, src/main/resources/templates/src/main/kotlin/MainVerticle.kt.ftl, src/main/resources/templates/src/test/java/TestMainVerticle.java.ftl, src/main/resources/templates/src/test/kotlin/TestMainVerticle.kt.ftl, src/test/java/io/vertx/starter/service/GeneratorTest.java
=> Support both Vert.x 4 and Vert.x 5

src/main/resources/templates/pom.xml.ftl
=> Starter with 5.0.0-SNAPSHOT uses incorrect launcher class in pom.xml

src/main/resources/starter.json
See https://github.com/eclipse-vertx/vertx-auth/pull/692
=> Added webauthn4j module

src/main/frontend/package-lock.json
Reverts vert-x3/vertx-starter#634
=> Revert "Bump nanoid from 3.3.7 to 3.3.8 in /src/main/frontend"

src/main/resources/starter.json
Closes #700 
Also, bump the snapshot version to 5.0.1
=> Make Vert.x 5.0.0 the new default version

.github/workflows/ci.yml, .github/workflows/set-versions.yml
`checkout@v4` and `setup-java@v4`
=> Upgrade GH Actions
